// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace School.Services.Entities;

public partial class AdvancePayment
{
    public double? JournalEntry { get; set; }

    public string Series { get; set; }

    public DateTime? TrxDate { get; set; }

    public string AccountNumber { get; set; }

    public string AccountDescription { get; set; }

    public double? DebitAmount { get; set; }

    public double? CreditAmount { get; set; }

    public string Description { get; set; }

    public string Reference { get; set; }

    public double? Pid { get; set; }

    public string ParentName { get; set; }

    public double? FatherIqama { get; set; }

    public double? Sid { get; set; }

    public double? StudentIqama { get; set; }

    public string StudentFullName { get; set; }

    public string Grade { get; set; }

    public double? Section { get; set; }

    public double? InvoiceNo { get; set; }

    public double? ReciptNo { get; set; }

    public double? Amount { get; set; }

    public string Payment { get; set; }

    public string Year { get; set; }
}