//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceZatcaDetail
    {
        public long DeviceZatcaDetailId { get; set; }
        public long SellerDeviceConfigurationId { get; set; }
        public string Mode { get; set; }
        public string CSR { get; set; }
        public string PrivateKey { get; set; }
        public string PubicKey { get; set; }
        public string SecretKey { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public long UpdateBy { get; set; }
    }
}
