// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class IntGlsourceTable
{
    public int SeqNum { get; set; }

    public string Reference { get; set; }

    public int? JournalNumber { get; set; }

    public short? TransactionType { get; set; }

    public DateTime? TransactionDate { get; set; }

    public DateTime? ReversingDate { get; set; }

    public string AccountNumber { get; set; }

    public string DistributionRef { get; set; }

    public decimal? CreditAmount { get; set; }

    public decimal? DebitAmount { get; set; }

    public short IntegrationStatus { get; set; }

    public string Error { get; set; }
}