// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class IntSalesDistributionSourceTable
{
    public int SeqNum { get; set; }

    public string Sopnumber { get; set; }

    public short Soptype { get; set; }

    public short DistType { get; set; }

    public string AccountNumber { get; set; }

    public decimal DebitAmount { get; set; }

    public decimal CreditAmount { get; set; }

    public string DistributionRef { get; set; }

    public short IntegrationStatus { get; set; }

    public string Error { get; set; }
}