// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class IntSalesInvoiceSourceTable
{
    public int SeqNum { get; set; }

    public string Sopnumber { get; set; }

    public short Soptype { get; set; }

    public string DocId { get; set; }

    public DateTime? DocDate { get; set; }

    public string CustomerNumber { get; set; }

    public string ItemNumber { get; set; }

    public decimal? Quantity { get; set; }

    public decimal? UnitPrice { get; set; }

    public short IntegrationStatus { get; set; }

    public string Error { get; set; }
}