// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class IntSalesPaymentSourceTable
{
    public int SeqNum { get; set; }

    public string Sopnumber { get; set; }

    public short Soptype { get; set; }

    public int? PaymentType { get; set; }

    public decimal? PaymentAmount { get; set; }

    public string CheckbookId { get; set; }

    public string CardName { get; set; }

    public string CheckNumber { get; set; }

    public string CreditCardNumber { get; set; }

    public string AuthorizationCode { get; set; }

    public DateTime? ExpirationDate { get; set; }

    public short IntegrationStatus { get; set; }

    public string Error { get; set; }
}