// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class InvInvoiceSummary
{
    public long InvoiceId { get; set; }

    public long InvoiceNo { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public string Status { get; set; }

    public string PublishedBy { get; set; }

    public string CreditNo { get; set; }

    public string CreditReason { get; set; }

    public string CustomerName { get; set; }

    public string ParentId { get; set; }

    public string IqamaNumber { get; set; }

    public decimal? TaxableAmount { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal ItemSubtotal { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }

    public string InvoiceType { get; set; }

    public long? InvoiceRefNo { get; set; }
    public string PaymentMethod { get; set; }

    public string EncodedInvoice { get; set; }
    public string InvoiceHash { get; set; }
    public string UUID { get; set; }
    public string ReportingStatus { get; set; }
    public string QRCodePath { get; set; }
    public string SignedXMLPath { get; set; }
    public string InvoicePdfPath { get; set; }
    public string ChequeNo { get; set; }
    public string EmailID { get; set; }
    public string MobileNo { get; set; }
    public string GPVoucherNo { get; set; }
    public string VATNo { get; set; }
    public string ParentName { get; set; }
    public string Nationality { get; set; }
    public bool? IsSentToZatca { get; set; }
    public string ClearedInvoice { get; set; }
    public string WarningMessage { get; set; }

    public string ErrorMessage { get; set; }
    public int? StatusCode { get; set; }
}