// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class OpenApplyStudentParentMap
{
    public int StudentParentMapid { get; set; }

    public int OpenApplyStudentId { get; set; }

    public int OpenApplyParentId { get; set; }

    public string PrincePrefix { get; set; }
}