// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class OpenApplyStudent
{
    public int Newid { get; set; }

    public int Id { get; set; }

    public int? SerialNumber { get; set; }

    public string CustomId { get; set; }

    public string ApplicantId { get; set; }

    public string Email { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Name { get; set; }

    public string OtherName { get; set; }

    public string PreferredName { get; set; }

    public string BirthDate { get; set; }

    public string Gender { get; set; }

    public int? EnrollmentYear { get; set; }

    public string FullAddress { get; set; }

    public string Address { get; set; }

    public string AddressIi { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string PostalCode { get; set; }

    public string Country { get; set; }

    public string Grade { get; set; }

    public string Campus { get; set; }

    public int? CampusId { get; set; }

    public string Status { get; set; }

    public string StatusLevel { get; set; }

    public DateTime? StatusChangedAt { get; set; }

    public string ManagebacStudentId { get; set; }

    public string MbId { get; set; }

    public DateTime? AppliedAt { get; set; }

    public DateTime? EnrolledAt { get; set; }

    public DateTime? InquiredAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string LatestActivityDate { get; set; }

    public string Nationality { get; set; }

    public string StudentId { get; set; }

    public string PassportId { get; set; }

    public string ProfilePhoto { get; set; }

    public DateTime? ProfilePhotoUpdatedAt { get; set; }

    public string ChecklistState { get; set; }

    public DateTime? InquiredDate { get; set; }

    public DateTime? AppliedDate { get; set; }

    public DateTime? AdmittedDate { get; set; }

    public DateTime? WaitListedDate { get; set; }

    public DateTime? DeclinedDate { get; set; }

    public DateTime? EnrolledDate { get; set; }

    public DateTime? WithdrawnDate { get; set; }

    public DateTime? GraduatedDate { get; set; }

    public string Representative { get; set; }

    public DateTime? EnrollmentDate { get; set; }

    public string SourceCampaign { get; set; }

    public DateTime? ContactDate { get; set; }

    public string AgentId { get; set; }

    public string IqamaNo { get; set; }

    public string MobilePhone { get; set; }

    public bool PrinceAccount { get; set; }

    public string PIdSchoolParentId { get; set; }
}