// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class OpenApplyParent
{
    public int Newid { get; set; }

    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string OtherName { get; set; }

    public string PreferredName { get; set; }

    public string ParentId { get; set; }

    public string Gender { get; set; }

    public string Prefix { get; set; }

    public string Phone { get; set; }

    public string MobilePhone { get; set; }

    public string Address { get; set; }

    public string AddressIi { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string PostalCode { get; set; }

    public string Country { get; set; }

    public string Email { get; set; }

    public string Employer { get; set; }

    public string BirthDate { get; set; }

    public string WorkPhone { get; set; }

    public string Nationality { get; set; }

    public string ArabicTitle { get; set; }

    public string HomeTelephone { get; set; }

    public string IqamaNo { get; set; }

    public string StudentId { get; set; }

    public string PassportId { get; set; }

    public string PIdSchoolParentId { get; set; }
}