//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerDeviceConfiguration
    {
        public long SellerDeviceConfigurationId { get; set; }
        public long SellerId { get; set; }
        public string UserName { get; set; }
        public string DeviceManufacturer { get; set; }
        public string DeviceName { get; set; }
        public string DeviceId { get; set; }
        public string SerialNumber { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public long UpdateBy { get; set; }
    }
}
