// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblBranchMaster
{
    public long BranchId { get; set; }

    public string BranchName { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }

    public virtual ICollection<TblSchoolMaster> TblSchoolMasters { get; set; } = new List<TblSchoolMaster>();
}