// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblCostCenterMaster
{
    public long CostCenterId { get; set; }

    public string CostCenterName { get; set; }

    public string Remarks { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }

    public string DebitAccount { get; set; }

    public string CreditAccount { get; set; }

    public virtual ICollection<TblGradeMaster> TblGradeMasters { get; set; } = new List<TblGradeMaster>();

    public virtual ICollection<TblStudent> TblStudents { get; set; } = new List<TblStudent>();
}