// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblContactInformation
{
    public long ContactId { get; set; }

    public long? SchoolId { get; set; }

    public string ContactPerson { get; set; }

    public string ContactPosition { get; set; }

    public string ContactTelephone { get; set; }

    public string ContactEmail { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }

    public virtual TblSchoolMaster School { get; set; }
}