// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblDocumentTypeMaster
{
    public long DocumentTypeId { get; set; }

    public string DocumentTypeName { get; set; }

    public string Remarks { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }

    public virtual ICollection<TblUploadDocument> TblUploadDocuments { get; set; } = new List<TblUploadDocument>();
}