// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblFeeGenerate
{
    public long FeeGenerateId { get; set; }

    public long SchoolAcademicId { get; set; }

    public long FeeTypeId { get; set; }

    public long GradeId { get; set; }

    public int GenerateStatus { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }
}