// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblFeePaymentPlan
{
    public long FeePaymentPlanId { get; set; }

    public long FeeTypeDetailId { get; set; }

    public decimal PaymentPlanAmount { get; set; }

    public DateTime DueDate { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsApproved { get; set; }

    public bool IsRejected { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }
}