// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblFeeGradewise
{
    public long FeeGradewiseId { get; set; }

    public long FeeTypeId { get; set; }

    public long FeeStructureId { get; set; }

    public long GradeId { get; set; }

    public decimal? FirstAmount { get; set; }

    public DateTime? FirstDueDate { get; set; }

    public decimal? SecondAmount { get; set; }

    public DateTime? SecondDueDate { get; set; }

    public decimal? ThirdAmount { get; set; }

    public DateTime? ThirdDueDate { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }
}