// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblFeeStatement
{
    public long FeeStatementId { get; set; }

    public string FeeStatementType { get; set; }

    public long? InvoiceNo { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public string PaymentMethod { get; set; }

    public string FeeType { get; set; }

    public decimal FeeAmount { get; set; }

    public decimal PaidAmount { get; set; }

    public long StudentId { get; set; }

    public long ParentId { get; set; }

    public string StudentName { get; set; }

    public string ParentName { get; set; }

    public long AcademicYearId { get; set; }

    public int? GradeId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }
}