// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblFeeTypeMaster
{
    public long FeeTypeId { get; set; }

    public string FeeTypeName { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }

    public bool IsPaymentPlan { get; set; }

    public bool IsTermPlan { get; set; }

    public string DebitAccount { get; set; }

    public string CreditAccount { get; set; }

    public bool IsPrimary { get; set; }

    public bool IsGradeWise { get; set; }
}