// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblGradeMaster
{
    public int GradeId { get; set; }

    public long CostCenterId { get; set; }

    public int? GenderTypeId { get; set; }

    public string GradeName { get; set; }

    public int SequenceNo { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }

    public string DebitAccount { get; set; }

    public string CreditAccount { get; set; }

    public virtual TblCostCenterMaster CostCenter { get; set; }

    public virtual ICollection<TblStudent> TblStudents { get; set; } = new List<TblStudent>();
}