// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblInvoiceTypeMaster
{
    public long InvoiceTypeId { get; set; }

    public string InvoiceTypeName { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }

    public string ReceivableAccount { get; set; }

    public string AdvanceAccount { get; set; }

    public string ReceivableAccountRemarks { get; set; }

    public string AdvanceAccountRemarks { get; set; }
}