// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblMenu
{
    public int MenuId { get; set; }

    public string Menu { get; set; }

    public string MenuCtrl { get; set; }

    public string MenuAction { get; set; }

    public int? ParentMenuId { get; set; }

    public int DisplaySequence { get; set; }

    public string FaIcon { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }
}