// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblNotificationGroupDetail
{
    public int NotificationGroupDetailId { get; set; }

    public int NotificationGroupId { get; set; }

    public int NotificationTypeId { get; set; }

    public string NotificationAction { get; set; }

    public string TableRecordId { get; set; }

    public string TableRecordColumnName { get; set; }

    public string OldValueJson { get; set; }

    public string NewValueJson { get; set; }

    public int CreatedBy { get; set; }
}