// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblNotificationGroup
{
    public int NotificationGroupId { get; set; }

    public int NotificationTypeId { get; set; }

    public int NotificationCount { get; set; }

    public string NotificationAction { get; set; }
}