// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblParent
{
    public long ParentId { get; set; }

    public string ParentCode { get; set; }

    public string ParentImage { get; set; }

    public string FatherName { get; set; }

    public string FatherArabicName { get; set; }

    public int FatherNationalityId { get; set; }

    public string FatherMobile { get; set; }

    public string FatherEmail { get; set; }

    public bool IsFatherStaff { get; set; }

    public string MotherName { get; set; }

    public string MotherArabicName { get; set; }

    public int MotherNationalityId { get; set; }

    public string MotherMobile { get; set; }

    public string MotherEmail { get; set; }

    public bool IsMotherStaff { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }

    public string FatherIqamaNo { get; set; }

    public string MotherIqamaNo { get; set; }

    public long? OpenApplyFatherId { get; set; }

    public long? OpenApplyMotherId { get; set; }

    public long? OpenApplyStudentId { get; set; }

    public virtual ICollection<TblStudent> TblStudents { get; set; } = new List<TblStudent>();
}