// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblStudentOpenApplyProcessed
{
    public long ProcessId { get; set; }

    public long StudentId { get; set; }

    public string StudentCode { get; set; }

    public string StudentImage { get; set; }

    public long? ParentId { get; set; }

    public string StudentName { get; set; }

    public string StudentArabicName { get; set; }

    public string StudentEmail { get; set; }

    public DateTime Dob { get; set; }

    public string IqamaNo { get; set; }

    public int NationalityId { get; set; }

    public int GenderId { get; set; }

    public DateTime AdmissionDate { get; set; }

    public int GradeId { get; set; }

    public long CostCenterId { get; set; }

    public long SectionId { get; set; }

    public string PassportNo { get; set; }

    public DateTime? PassportExpiry { get; set; }

    public string Mobile { get; set; }

    public string StudentAddress { get; set; }

    public int StudentStatusId { get; set; }

    public DateTime? WithdrawDate { get; set; }

    public int? WithdrawAt { get; set; }

    public string WithdrawYear { get; set; }

    public decimal? Fees { get; set; }

    public bool IsGpintegration { get; set; }

    public int TermId { get; set; }

    public string AdmissionYear { get; set; }

    public bool PrinceAccount { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }

    public string PIdSchoolParentId { get; set; }
}