// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblSchoolTermAcademic
{
    public int SchoolTermAcademicId { get; set; }

    public int SchoolAcademicId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsApproved { get; set; }

    public bool IsRejected { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }

    public string TermName { get; set; }

    public virtual TblSchoolAcademic SchoolAcademic { get; set; }
}