// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblSchoolMaster
{
    public long SchoolId { get; set; }

    public string SchoolNameEnglish { get; set; }

    public string SchoolNameArabic { get; set; }

    public long BranchId { get; set; }

    public long? CountryId { get; set; }

    public string City { get; set; }

    public string Address { get; set; }

    public string Telephone { get; set; }

    public string SchoolEmail { get; set; }

    public string WebsiteUrl { get; set; }

    public string VatNo { get; set; }

    public string Logo { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }

    public virtual TblBranchMaster Branch { get; set; }

    public virtual ICollection<TblContactInformation> TblContactInformations { get; set; } = new List<TblContactInformation>();

    public virtual ICollection<TblSchoolAcademic> TblSchoolAcademics { get; set; } = new List<TblSchoolAcademic>();

    public virtual ICollection<TblSchoolAccountInfo> TblSchoolAccountInfos { get; set; } = new List<TblSchoolAccountInfo>();

    public virtual ICollection<TblSchoolLogo> TblSchoolLogos { get; set; } = new List<TblSchoolLogo>();
}