// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblSchoolAcademic
{
    public int SchoolAcademicId { get; set; }

    public long? SchoolId { get; set; }

    public string AcademicYear { get; set; }

    public DateTime PeriodFrom { get; set; }

    public DateTime PeriodTo { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }

    public string DebitAccount { get; set; }

    public string CreditAccount { get; set; }

    public bool? IsCurrentYear { get; set; }

    public virtual TblSchoolMaster School { get; set; }

    public virtual ICollection<TblSchoolTermAcademic> TblSchoolTermAcademics { get; set; } = new List<TblSchoolTermAcademic>();
}