// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblSiblingDiscountMaster
{
    public int DiscountId { get; set; }

    public int ChildrenNo { get; set; }

    public decimal DiscountPercent { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }

    public decimal StaffDiscountPercent { get; set; }
}