// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblUser
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string UserArabicName { get; set; }

    public string UserEmail { get; set; }

    public string UserPhone { get; set; }

    public string UserPass { get; set; }

    public string ProfileImg { get; set; }

    public int RoleId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }

    public bool? IsApprover { get; set; }

    public string Otp { get; set; }

    public DateTime? OtpExpiration { get; set; }
}