// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblUploadDocument
{
    public long UploadedDocId { get; set; }

    public int DocFor { get; set; }

    public long DocType { get; set; }

    public long DocForId { get; set; }

    public string DocNo { get; set; }

    public string DocPath { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }

    public virtual TblDocumentTypeMaster DocTypeNavigation { get; set; }
}