// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class TblVatMaster
{
    public long VatId { get; set; }

    public int FeeTypeId { get; set; }

    public decimal VatTaxPercent { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime UpdateDate { get; set; }

    public int UpdateBy { get; set; }

    public string DebitAccount { get; set; }

    public string CreditAccount { get; set; }
}