// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.Entities;

public partial class Transaction
{
    public int TransactionId { get; set; }

    public string TransactionType { get; set; }

    public int? TransactionNo { get; set; }
}