//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniformDetail
    {
        public int UniformDetailID { get; set; }
        public long InvoiceNo { get; set; }
        public string Description { get; set; }
        public string Grade { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string Quantity { get; set; }
        public string UnitPrice { get; set; }
        public string TaxableAmount { get; set; }
        public string Discount { get; set; }
        public string TaxRate { get; set; }
        public string TaxAmount { get; set; }
        public string ItemSubtotal { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    }
}
