// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace School.Services.ZatcaEntities;

public partial class InvoiceDetail
{
    public long Id { get; set; }

    public string InvoiceNo { get; set; }

    public string Description { get; set; }

    public decimal? Discount { get; set; }

    public decimal? TaxableAmount { get; set; }

    public decimal? TaxRate { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? ItemSubtotal { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string UpdatedBy { get; set; }
}