// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
//using System;
//using System.Collections.Generic;

//namespace School.Services.ZatcaEntities;

//public partial class UniformDetail
//{
//    public int UniformDetailId { get; set; }

//    public string InvoiceNo { get; set; }

//    public string Description { get; set; }

//    public string Grade { get; set; }

//    public string Color { get; set; }

//    public string Size { get; set; }

//    public string Quantity { get; set; }

//    public string UnitPrice { get; set; }

//    public string TaxableAmount { get; set; }

//    public string Discount { get; set; }

//    public string TaxRate { get; set; }

//    public string TaxAmount { get; set; }

//    public string ItemSubtotal { get; set; }

//    public DateTime? CreatedOn { get; set; }

//    public string CreatedBy { get; set; }

//    public DateTime? UpdatedOn { get; set; }

//    public string UpdatedBy { get; set; }
//}