// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
//using System;
//using System.Collections.Generic;
//using Microsoft.EntityFrameworkCore;

//namespace School.Services.ZatcaEntities;

//public partial class ZatcaContext : DbContext
//{
//    public ZatcaContext(DbContextOptions<ZatcaContext> options)
//        : base(options)
//    {
//    }

//    public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }

//    public virtual DbSet<InvoicePayment> InvoicePayments { get; set; }

//    public virtual DbSet<InvoiceSummary> InvoiceSummaries { get; set; }

//    public virtual DbSet<UniformDetail> UniformDetails { get; set; }

//    protected override void OnModelCreating(ModelBuilder modelBuilder)
//    {
//        modelBuilder.Entity<InvoiceDetail>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("pk_InvoiceDetail");

//            entity.ToTable("InvoiceDetail");

//            entity.Property(e => e.Id).HasColumnName("ID");
//            entity.Property(e => e.CreatedBy)
//                .HasMaxLength(50)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
//            entity.Property(e => e.Description)
//                .HasMaxLength(150)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.Discount).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.InvoiceNo)
//                .HasMaxLength(50)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.ItemSubtotal).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.TaxAmount).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.TaxRate).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.TaxableAmount).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.UpdatedBy)
//                .HasMaxLength(50)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.UpdatedOn).HasColumnType("datetime");
//        });

//        modelBuilder.Entity<InvoicePayment>(entity =>
//        {
//            entity.ToTable("InvoicePayment");

//            entity.Property(e => e.PaymentAmount).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.PaymentMethod)
//                .IsRequired()
//                .HasMaxLength(200);
//            entity.Property(e => e.PaymentReferenceNumber)
//                .IsRequired()
//                .HasMaxLength(200);
//            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
//        });

//        modelBuilder.Entity<InvoiceSummary>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("pk_id");

//            entity.ToTable("InvoiceSummary");

//            entity.Property(e => e.Id).HasColumnName("ID");
//            entity.Property(e => e.Address)
//                .HasMaxLength(250)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.ChequeNo)
//                .HasMaxLength(50)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.CreatedBy)
//                .HasMaxLength(50)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
//            entity.Property(e => e.CreditNo)
//                .HasMaxLength(50)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.CreditReason).UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.CustomerName)
//                .HasMaxLength(100)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.EmailId)
//                .HasMaxLength(50)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS")
//                .HasColumnName("EmailID");
//            entity.Property(e => e.EncodedInvoice).UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.GpvoucherNo)
//                .HasMaxLength(50)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS")
//                .HasColumnName("GPVoucherNo");
//            entity.Property(e => e.InvoiceDate).HasColumnType("datetime");
//            entity.Property(e => e.InvoiceHash).UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.InvoiceNo)
//                .HasMaxLength(50)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.InvoiceType)
//                .HasMaxLength(50)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.IqamaNumber).HasMaxLength(50);
//            entity.Property(e => e.MobileNo).HasMaxLength(50);
//            entity.Property(e => e.Nationality).HasMaxLength(100);
//            entity.Property(e => e.ParentId)
//                .HasMaxLength(50)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS")
//                .HasColumnName("ParentID");
//            entity.Property(e => e.ParentName)
//                .HasMaxLength(100)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.PaymentMethod)
//                .HasMaxLength(50)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.PublishedBy)
//                .HasMaxLength(50)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.QrcodePath)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS")
//                .HasColumnName("QRCodePath");
//            entity.Property(e => e.RefId).HasColumnName("RefID");
//            entity.Property(e => e.ReportingStatus)
//                .HasMaxLength(100)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.SignedXmlpath).HasColumnName("SignedXMLPath");
//            entity.Property(e => e.Status)
//                .HasMaxLength(10)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.UpdatedBy)
//                .HasMaxLength(50)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS");
//            entity.Property(e => e.UpdatedOn).HasColumnType("datetime");
//            entity.Property(e => e.Uuid)
//                .HasMaxLength(800)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS")
//                .HasColumnName("UUID");
//            entity.Property(e => e.Vatno)
//                .HasMaxLength(50)
//                .UseCollation("SQL_Latin1_General_CP1256_CI_AS")
//                .HasColumnName("VATNo");
//        });

//        modelBuilder.Entity<UniformDetail>(entity =>
//        {
//            entity.HasKey(e => e.UniformDetailId).HasName("pk_UniformDetails_id");

//            entity.Property(e => e.UniformDetailId).HasColumnName("UniformDetailID");
//            entity.Property(e => e.Color).HasMaxLength(50);
//            entity.Property(e => e.CreatedBy).HasMaxLength(50);
//            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
//            entity.Property(e => e.Description).HasMaxLength(150);
//            entity.Property(e => e.Discount).HasMaxLength(50);
//            entity.Property(e => e.Grade).HasMaxLength(50);
//            entity.Property(e => e.InvoiceNo).HasMaxLength(50);
//            entity.Property(e => e.ItemSubtotal).HasMaxLength(50);
//            entity.Property(e => e.Quantity).HasMaxLength(50);
//            entity.Property(e => e.Size).HasMaxLength(50);
//            entity.Property(e => e.TaxAmount).HasMaxLength(50);
//            entity.Property(e => e.TaxRate).HasMaxLength(50);
//            entity.Property(e => e.TaxableAmount).HasMaxLength(50);
//            entity.Property(e => e.UnitPrice).HasMaxLength(50);
//            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
//            entity.Property(e => e.UpdatedOn).HasColumnType("datetime");
//        });

//        OnModelCreatingPartial(modelBuilder);
//    }

//    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
//}